matrix:
  include:
    - language: node_js
      node_js: '12'
      addons:
        sonarcloud:
          organization: "swsnu"
          token: 
            secure: "HM+A0xfMg81KoG9WWwR3YFhvW6gO2UDq67vsy7vsSR79i40cNaP/qYAFMKS0HxPTlvXxP/KMfCG2i4Ml6FhbOvG0yXJj6tTl2hVDCBh6XD7WdwEXMoB8kF//4zjlcWkpGJ/tM9GZfDVerNJ1MtmnL4grPdZDjbbk8ERvEfeNiQd/4J3+8MLlJRBLJCE9gS/2qGqN/NDu9K7jLjC0rY9P77AMW+WqRxmgmTAtQBOZyqTbkJQhAm0ww0G2iuqHqbdxNUXAoc+b86fKNHqnShDOxaVNErM6I2SM/Wmb4FNDKK7GGevTi/AGVI1kSF/i276SGpC58ovL/okRJIuJ5mgF5dJg50ojs1RrFKbwZnIX9hyXqzUAFyV3PJsnKiFWuuFrKLU2j0yExD4gv9uTa7V79RTFTHwOMTlstiK6HSxf7aoZqTs8u/hb6h6mkRNeaJdHKqFEMwnSt9/7UfEd86DHzbjYyuCJC2lMc5omxFAhqBpZSD47WtiuGZttaAvpfI2r/WglAntpP8cOlMAGlDqwSaCKV1ZOfP9hgELcf7QYgANUtFVDuokJ4+Aqt1MNWuzLgwQFRb9Yph1FWb+5nVq5AwLwHIuGf24KO3a23J8D2VsbbRqCL1HafZ/u1aWFmsBFBSces8yHTLdq672AWp/DoWqFaI5YO2rYe6pgjncCfiM="
      cache:
        - yarn: true
      before_install:
        - cd frontend
      install:
        - yarn install
      script:
        - ./node_modules/.bin/eslint src/
        - yarn test --coverage --watchAll=false
        - cd .. && sonar-scanner

    - language: python
      python: '3.7'
      cache:
        - pip: true
      before_install:
        - cd backend
      install:
        - pip install -r requirements.txt
      script:
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
