matrix:
  include:
    - language: node_js
      node_js: '12'
      addons:
        sonarcloud:
          organization: "swsnu"
          token:
            secure: "Hw2NDKPHqZPBBDyXMcva8A2NQbwUg2yVJ5s9LUdVFtd8DkmipEKbLR3xbB/NwJVZyKSDGhrOc6TgsXZCDRjGXwZO0Es2g8UBDESPvr3JqO3rzMag3/IXnGXOdJ+L3E2KLcZv8PQkqBfG+G9/+Tz5fxXSx6kEsA1KhFY4MFkBCDgNULYX6XOREDGe5JKpKPEFHGuraAp/oEIHvzqzvPZI+vZBAcGXNV9SbglY2anryElETfhODEDR2j2+EWvxZZ5NiyVnBDQfGcJBSUlBEDWVGlc/Yd4hpsJyD0yGQKFZBrQ+3inlcfC6r2zt1uRiEmhkdVvksgbh4du7U15Hv9waANIqLQJP+ckaNKMBMA/RjyHi8dvFaebFR63eH8bC1OMvXjRTdzP+nBwBDD0JwtKL65Xif74rmQbXDuQjSOGezF03XmKf8gH9xWpajQ9SntTKK7U71hhJeiE0JNojOMOwikV0JE5SKdX/2v9Wd3Zw9+gwRNCO1pyH00EABzMXjY9adKJF2ihG52c/zSciqS3UWRWjuPub5e+nAe/xbsB39ogHEV/5PqLmuaDLRJCThAT5wyaUk/AwtKTx0/664TYNE+U3ntoewVnZhaUHY0mc3IOFdU336/jfpjSgHigCwnrD5fBLOG+38Ua3Uov+e3LXExpLV2K5Q/gr4ECLPcsvOSQ="
      cache:
        - yarn: true
      before_install:
        - cd frontend
      install:
        - yarn install
      script:
        - ./node_modules/.bin/eslint src/
        - yarn test --coverage --watchAll=false
        - cd .. && sonar-scanner

    - language: python
      python: '3.7'
      cache:
        - pip: true
      before_install:
        - cd backend
      install:
        - pip install -r requirements.txt
      script:
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
