matrix:
  include:
    - language: node_js
      node_js: '12'
      addons:
        sonarcloud:
          organization: "swsnu"
          token:
            secure: "d/fdmbRTH2+nYq5GjbvYrALny339Naqy4T1B+YLoUiZPpkei3GsJmOX/uPoa2DG5qlVsz4fkPNIS4I2ztnLD4NEHDdJLzC8BfQ6o6Tv6gCu3bdfkprZ1s+OFnR8yrjMhjyFl+lkrBbQomCeKRjS0HzJAXnEV4m7g3AZFkrxJGS4g+IJsBV3MUACE1ioybzMuJ28/X+UIuZkdajsBhbtsFsSZZbfhgvVXxSjX278BDFFvA0tsDdX6Hna/ZPT/WVtIZe46soZ7izVJwFfbJz10RAykrY6nOToPG9wz5q2w0ds5gzyX8YYtxXCMvcDioyrjQAgOB2SfAVkv3ImVMnSIRh14w+sKYigMh84y8snKzZR5OT4DVhjtI7zx8/4gayda5rrMepSdd1I97ZzH+WRfA4XBEKCghMcIVAG6NUBGxN4PoJ+qgtG1OSKqqsopDUR+19hjUIW/iRiRCapWL48+/5ylFSUn0Lnp9yZQGbM1PK0jx3Xph6dj3IQNEGBpl4PAAQdGAb4nkQWLCCguIXgHLQ+WReGFg34cOTEHF9kLDrsyXGRtyvfyQVMf2gNSyFbNl6HJ+E6/HprwGJ4DGN22b1cfQcLZPBpNOfuxd8o5EcctHjVSgcnv5nxy4xhD4bj+UacYHJ7IOaf8cY0MR8QyVEvg9UDKeFWrRgD9lxdatXo="
      cache:
        - yarn: true
      before_install:
        - cd frontend
      install:
        - yarn install
      script:
        - ./node_modules/.bin/eslint src/
        - yarn test --coverage --watchAll=false
        - cd .. && sonar-scanner

    - language: python
      python: '3.7'
      cache:
        - pip: true
      before_install:
        - cd backend
      install:
        - pip install -r requirements.txt
      script:
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
