# Generated by Django 3.1.2 on 2020-11-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0002_auto_20201110_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
