# Generated by Django 3.1.2 on 2020-11-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0003_auto_20201112_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
