# Generated by Django 3.1.2 on 2020-11-12 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0006_auto_20201112_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_userpreference', to='almanac.language'),
        ),
    ]
