# Generated by Django 3.1.2 on 2020-11-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0007_auto_20201112_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='privacy',
            field=models.IntegerField(default=1),
        ),
    ]
