# Generated by Django 3.1.2 on 2020-11-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0008_auto_20201112_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='join_requests',
            field=models.ManyToManyField(related_name='join_requests_userpreference', to='almanac.Group'),
        ),
    ]
