# Generated by Django 3.1.2 on 2020-12-05 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almanac', '0009_userpreference_join_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ManyToManyField(related_name='image_event', to='almanac.Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_editor_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=models.ManyToManyField(related_name='tag_event', to='almanac.Tag'),
        ),
    ]
